### ISSUE TITLE
Update to 4.3.1

### ISSUE THREAD

**Issue by luigisaggese** [localytics/localytics-xamarin#11]
Any update for Xamarin?

**Comment by duckwaffle** [comment]
Considering the SDK is now at 4.4.1, it would be nice to get an updated Xamarin component :)

**Comment by abashyam** [comment]
A Xamarin Nuget Package is available with the SDK 5.1 https://www.nuget.org/packages/LocalyticsXamarin/
Closing the issue in favor of using Nuget packages rather than components.
