### ISSUE TITLE
Update makefile to support Java 1.8

### ISSUE THREAD

**Issue by duckwaffle** [localytics/localytics-xamarin#13]
When following the instructions to build the component, on a system using pretty much any stable version of Xamarin released this year you will get an error saying the make process doesn't support Java greater than 1.7.

Considering that Java 1.8 is pretty much a requirement for Xamarin development these days, it would probably be a good idea to update the build process.

**Comment by noxryan** [comment]
I put up a PR for this a while back but did not receive a response:

https://github.com/localytics/localytics-xamarin/pull/12

**Comment by abashyam** [comment]
The PR has been merged. Closing the issue.
