### ISSUE TITLE
Localytics Playstore version 

### ISSUE THREAD

**Issue by kodejack** [localytics/localytics-xamarin#73]
The Android Playstore has rejected the app and is suggesting we need to use Localytics v6.3.9 but nuget only goes up to 6.3.2.   

Can this be update to support the latest version. 

<img width="893" alt="Screenshot 2024-10-03 at 10 33 27" src="https://github.com/user-attachments/assets/36c4fb84-87b6-4f05-8cfc-bc1d35cda5ad">

**Comment by ssharma-Localytics** [comment]
@kodejack 6.3.9 is the Android version for the Xamarin wrapper
The Xamarin 6.3.2 contains Android SDK version 6.4.0 and should get accepted.

**Comment by kodejack** [comment]
Thanks for the update
